site_name: Golang Tutorial
site_url: https://golangtutorial.com/
nav:
  - Home: chapter_1/index.md
  - Глава 1. Основы языка Go:
      - Первая программа: chapter_1/firstProg.md
      - Переменные: chapter_1/var.md
      - Типы данных: chapter_1/typeOf.md
      - Арифметические операции: chapter_1/arith.md
      - Константы: chapter_1/const.md
      - Условные выражения и условные конструкции: chapter_1/condit.md
      - Массивы и срезы: chapter_1/array.md
      - Циклы: chapter_1/cicle.md
  - Глава 2. Функции, пакеты и другое:
      - Work still in progress: chapter_2/function.md
theme: readthedocs
markdown_extensions:
    - extra
    - tables
    - mdx_math:
        enable_dollar_delimiter: True
    - fenced_code
theme: readthedocs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML